# Generated by Django 3.1.7 on 2021-03-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suburb', models.CharField(max_length=250)),
                ('rooms', models.IntegerField()),
                ('housetype', models.CharField(max_length=3)),
                ('seller', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('price', models.FloatField(null=True)),
            ],
        ),
    ]
